# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "rG1d3mTtR0P7qqFKyXSz13naRgQDIadYpicPmzrpq5P7VJ6ef1HsrYqr55xjRduP6ldFf+f8OKd2ZCrBEp30Z7wVVKL97OKROHPBIIBFUQr55hom3owNi1jToHjxCM9JwzJKwK32M1mo0AcS4nbGORvEVUR3efFfnqz6pVNuul+xi/P3IgxFXJNHRiLcC7i1Htf9CNrS5sKEuNt3H9dF38aCHjTkz38moZI+cIDBBxwPsr7EoOOeo3kFpuGO74Br482DHmgPZmoMP85png6+yxwiW3DXnsbkquYWHNNQehM+eWe2AD4ezkemqCiq7dhwglyo149+j/XJKWdknDy/4RTu8keDruB08dzgFH9AmtQtddyRLTObTqnwiID3SYCThWuuee5zrIsZcbN9NYKkXqgV2eWgFvaG7mI8e47+ehVvfNCjknsCsRpqxpylXt4v95nw3XbDl1t5DOvyyMw5cXBm5xdVfogwvJi6Z5bSWtrzZpHGamObuOQ5zA/G041BpIgLv57Z2QrbeQDsgQUh11PWOsx5LnmdpzOt2d2wU+Ffk+06QhvGJYJ/z0SlPuqP0F7Ue/TQrwJNZNRJ1sqjEaSZc6Qo4KAiKtddmMnZ70d2JK0Wd3AXvju/28Da6PwR/EV3YxQqnzLasd7tPa8iVcavMaCp7dLNMKENsY9sPFI="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
